spring.application.name=qrordering
spring.datasource.url=jdbc:postgresql://localhost:5432/qr_ordering_system
spring.datasource.username=postgres
spring.datasource.password=Jagadish1409

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true